name: CI

on:
  schedule:
    - cron: '10 20 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '**.yml'
  push:
    branches:
      - main
    paths:
      - '**.zig'
      - '**.yml'

jobs:
  test-linux:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        zig-version: [master, 0.12.0]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
      - name: Install deps
        run: |
          sudo apt update && sudo apt install -y valgrind
      - name: Run tests
        run: |
          make test
      - name: Run examples
        run: |
          make run
      - name: Memory leak detect
        run: |
          zig build -Dcpu=baseline --verbose

          BINS=("./zig-out/bin/basic" "./zig-out/bin/advanced")
          for bin in ${BINS[@]}; do
            valgrind --leak-check=full --tool=memcheck \
            --show-leak-kinds=all --error-exitcode=1 ${bin}
          done

  test-macos:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        zig-version: [master, 0.12.0]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: Run examples
        run: |
          make run
